#!/bin/bash
# scritp para obtener la temperatura interna de la ups del rack

function usage()
{
cat <<END
  Usage: $0 -w NUM -c NUM [ -h ]
    -w: warning temperature level
    -c: critical temperature level
    -h: print this help
END
}


function is_num()
{
  printf %d $1 &>/dev/null
  return $?
}

#function bigger()
#{
#  op1="$1"
#  op2="$2"
#  res=$(echo "$op1 > $op2" | bc)
#  [ "$res" == "1" ] && return 0
#  return 1
#}

function smaller()
{
  op1="$1"
  op2="$2"
  res=$(echo "$op1 < $op2" | bc)
  [ "$res" == "1" ] && return 0
  return 1
}

OPS=$(getopt w:c:h:: "$@")

eval set -- "$OPS"

while true ; do
  case "$1" in
    -w) WARN=$2 ; shift 2 ;;
    -c) CRITIC=$2 ; shift 2 ;;
    -h) usage ; exit 0 ;;
    --) shift ; break ;;
  esac
done

# return values
# UNKNOWN = 3
# CRITICAL = 2
# WARNING = 1
# OK = 0

if [ "${WARN}x" == "x" -o  "${CRITIC}x" == "x" ] ; then
  echo "UPSTERM UNKNOWN: Invalid -w nor -c arguments"
  exit 3
fi

if ! is_num "$WARN" || ! is_num "$CRITIC" ; then
  echo "UPSTERM UNKNOWN: Invalid -w nor -c arguments"
  exit 3
fi

smaller "$CRITIC"  "$WARN" && {
  echo "UPSTERM UNKNOWN: -c value smaller than -w"
  exit 3
}

temperature=$(apcaccess 2>&1 | grep ^ITEMP | sed -e 's/[^0-9\.]//g')


if [ $? -gt 0 ] ; then 
  echo "UPSTERM UNKNOWN: error executing apcaccess"
  exit 3
fi

if [ "${temperature}X" == "X" ] ; then
  echo "UPSTERM UNKNOWN: some read error using apcaccess"
  exit 3
fi

smaller "$CRITIC"  "$temperature"  && {
  echo "UPSTERM CRITICAL: Temp=$temperature | temp=$temperature;$WARN;$CRITIC"
  exit 2
}

smaller "$WARN"  "$temperature" && {
  echo "UPSTERM WARNING: Temp=$temperature | temp=$temperature;$WARN;$CRITIC"
  exit 1
}

echo "UPSTERM OK: Temp=$temperature | temp=$temperature;$WARN;$CRITIC"
exit 0

